#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Isra.Xam.RetoFinal.Droid.Resource", IsApplication=true)]

namespace Isra.Xam.RetoFinal.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int btnAnalizaFoto = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int btnCamara = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int btnConsultaFoto = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int btnConsultaRegistros = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int btnRegistraResultados = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int btnRegistrarFoto = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnRegistrarReto = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int editTextNombrePaciente = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int editTextUsuario = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int imageViewFoto = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int scrollView1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int textViewEmail = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int textViewRegistros = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int txtOutput = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConsultaExpedientes = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RegistraExpediente = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DescApp = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int DevName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int btnConsultaFoto = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int btnRegistrarFoto = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btnRegistrarReto = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
